export default {
  FINISHEDTYPE: 'FINISHEDTYPE',
  NOPROGRESSTYPE: 'NOPROGRESSTYPE',
  PROGRESSINGTYPE: 'PROGRESSINGTYPE',
  REFUSEDTYPE: 'REFUSEDTYPE',

  EMPLOYEESPECIALOPERATORVIEW: 'EMPLOYEESPECIALOPERATORVIEW',
  EMPLOYEESPECIALPROGRESS2: 'EMPLOYEESPECIALPROGRESS2',
  EMPLOYEESPECIALPROGRESS3: 'EMPLOYEESPECIALPROGRESS3',
}
