/**
 * Created by huangye on 2017/11/24.
 */
export default {
  EMPLOYEESPECIALOPERATOR: 'EMPLOYEESPECIALOPERATOR',
  EMPLOYEEFUNDSPECIALPROGRESSTWO: 'EMPLOYEEFUNDSPECIALPROGRESSTWO',
  SNOPROCESS: 'SNOPROCESS',
}
