/**
 * Created by huangye on 2017/11/24.
 */
export default {
  EMPLOYEESPECIALOPERATOR: 'EMPLOYEESPECIALOPERATOR',
  EMPLOYEEFUNDSPECIALPROGRESSTWO: 'EMPLOYEEFUNDSPECIALPROGRESSTWO',
  EMPLOYEEFUNDSPECIALPROGRESSTHREE: 'EMPLOYEEFUNDSPECIALPROGRESSTHREE',
  SNOPROCESS: 'SNOPROCESS',
  SPROCESSED: 'SPROCESSED',
  SFINISHED: 'SFINISHED',
  SREFUSED: 'SREFUSED'
}
