export default {
  CFINISHEDTYPE: 'CFINISHEDTYPE',
  CNEXTMONTHHANDLETYPE: 'CNEXTMONTHHANDLETYPE',
  CREFUSEDTYPE: 'CREFUSEDTYPE',
  CTHISMONTHHANDLETYPE: 'CTHISMONTHHANDLETYPE',

  COMPANYTASKPROGRESS2TYPE: 'COMPANYTASKPROGRESS2TYPE',
  COMPANYTASKPROGRESSCHANGEINFOTYPE: 'COMPANYTASKPROGRESSCHANGEINFOTYPE',
  COMPANYTASKPROGRESSSENDINFOTYPE: 'COMPANYTASKPROGRESSSENDINFOTYPE',
  COMPANYTASKPROGRESSTRANSFERINFOTYPE: 'COMPANYTASKPROGRESSTRANSFERINFOTYPE',
  COMPANYTASKPROGRESSTYPEINFOTYPE: 'COMPANYTASKPROGRESSTYPEINFOTYPE',
}
