/**
 * Created by huangye on 2018/1/19.
 */
export default {
  STEP1: 'STEP1',
  STEP2: 'STEP2',
  FUNDYEARADJUSTMAINTAIN: 'FUNDYEARADJUSTMAINTAIN',
  FUNDYEARADJUSTSTATUS: 'FUNDYEARADJUSTSTATUS',
  FUNDYEARADJUSTVIEWDIFFERENCE: 'FUNDYEARADJUSTVIEWDIFFERENCE'
}
