export default {
  COMPANYSOCIALSECURITYCHANGEINFOTYPE: 'COMPANYSOCIALSECURITYCHANGEINFOTYPE',
  COMPANYSOCIALSECURITYENDINFOTYPE: 'COMPANYSOCIALSECURITYENDINFOTYPE',
  COMPANYSOCIALSECURITYMANAGETYPE: 'COMPANYSOCIALSECURITYMANAGETYPE',
  COMPANYSOCIALSECURITYPROGRESS2TYPE: 'COMPANYSOCIALSECURITYPROGRESS2TYPE',
  COMPANYSOCIALSECURITYTYPE: 'COMPANYSOCIALSECURITYTYPE',
}
