/**
 * Created by huangye on 2018/1/16.
 */
export default {
  COMPANYFUNDTASKLIST: 'COMPANYFUNDTASKLIST',
  COMPANYFUNDTASKPROGRESSTWO: 'COMPANYFUNDTASKPROGRESSTWO',
  COMPANYFUNDTASKPROGRESSTHREE: 'COMPANYFUNDTASKPROGRESSTHREE',
  LNOPROCESS: 'LNOPROCESS',
  LPROCESSING: 'LPROCESSING',
  LFINISHED: 'LFINISHED',
  LREFUSED: 'LREFUSED'
}
