export default {
  COMPANYSOCIALSECURITYNEWTYPE: 'COMPANYSOCIALSECURITYNEWTYPE',
  EMPLOYEESOCIALSECURITYINFO: 'EMPLOYEESOCIALSECURITYINFO',
  EMPLOYEESOCIALSECURITYSEARCH: 'EMPLOYEESOCIALSECURITYSEARCH',
}
