export default {
  FINISHHANDLETYPE: 'FINISHHANDLETYPE',
  NEXTMONTHHANDLETYPE: 'NEXTMONTHHANDLETYPE',
  REFUSEHANDLETYPE: 'REFUSEHANDLETYPE',
  THISMONTHHANDLETYPE: 'THISMONTHHANDLETYPE',

  EMPLOYEECOMMCIALOPERATOR: 'EMPLOYEECOMMCIALOPERATOR',
  EMPLOYEEOPERATORVIEW: 'EMPLOYEEOPERATORVIEW',
}
