export default {
  TRANSFER_LIST: "TRANSFER_LIST",
  REIMBURSEMENT_LIST: "REIMBURSEMENT_LIST",
  TRANSFER_INSERT: "TRANSFER_INSERT",
  REIMBURSEMENT_INSERT: "REIMBURSEMENT_INSERT",
  TRANSFER_UPDATE: "TRANSFER_UPDATE",
  REIMBURSEMENT_UPDATE: "REIMBURSEMENT_UPDATE",
};

