import SocialSecurityReconCilate from './social_security_recon_cilate'
import SocialSecurityReconCilateDetail from './social_security_recon_cilate_child/social_security_recon_cilate_detail'
export default {
  socialSecurityReconCilate: SocialSecurityReconCilate,
  socialSecurityReconCilateDetail:SocialSecurityReconCilateDetail
}
