/**
 * Created by huangye on 2018/1/15.
 */
export default {
  EMPLOYEETRANSFEROPERATOR: 'EMPLOYEESPECIALOPERATOR',
  EMPLOYEEFUNDTRANSFERPROGRESSTWO: 'EMPLOYEEFUNDTRANSFERPROGRESSTWO',
  TNOPROCESS: 'TNOPROCESS',
  TPROCESSED: 'TNOPROCESS',
  TREFUSED: 'TNOPROCESS'
}
